#include "varia/VAssets.source"
#include "varia/VGameContext.source"
#include "varia/VGameloop.source"
#include "varia/VSimulation.source"
#include "varia/VSystemEvents.source"
#include "varia/VSystemCallbacks.source"